spring:
  datasource:
    url: jdbc:mysql://yaho-dev-db.c5kimq6w0czs.ap-northeast-2.rds.amazonaws.com:3306/yaho
    username: root
    password: Yyaho29627qlalfdldi!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

kakao:
  client_id: 3fe9748de9767b5649437add91e54655
  redirect_uri: http://localhost:5173/oauth/callback/kakao
  client_secret: XUrvKHSPQqGQmWqGWYoGcvEhS4rM9IT6
  token_uri: https://kauth.kakao.com/oauth/token
  user_info_uri: https://kapi.kakao.com/v2/user/me

cloud:
  aws:
    s3:
      bucket: yahobucket
      path:
        mvp : mvp
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}